[CP-SAT] Fix build with abseil 20230802
The latest release of abseil (20230802) provides support for
`absl::int128` to string type conversion [^1]; now adding a custom
`AbslStringify` for `absl::int128` can cause the following build
problem (output truncated):

    /tmp/or-tools-20230829-202426-ykzj92/or-tools-9.7/ortools/sat/cuts.cc: In member function ‘std::string operations_research::sat::CutData::DebugString() const’:
    /tmp/or-tools-20230829-202426-ykzj92/or-tools-9.7/ortools/sat/cuts.cc:79:36: error: no matching function for call to ‘StrCat(const char [13], const absl::lts_20230802::int128&, const char [2])’
       79 |   std::string result = absl::StrCat("CutData rhs=", rhs, "\n");
          |                        ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~

Fix that by guarding the `AbslStringify` definition to pre-abseil
20230802 only.

[^1]: https://github.com/abseil/abseil-cpp/commit/34eb767645347f100bdd66fc1e35eee96e357961

Signed-off-by: Ruoyu Zhong <zhongruoyu@outlook.com>