pdlp: Fix test when using pytest 8.4.0
note: test_lp was considered as a test leading to the error
```sh
(cd build && ctest -C Release -R "python_pdlp_")
Test project .../build
    Start 175: python_pdlp_pdlp_test
1/2 Test #175: python_pdlp_pdlp_test .............***Failed    1.94 sec
============================= test session starts ==============================
platform linux -- Python 3.13.2, pytest-8.4.0, pluggy-1.6.0
...
../../../ortools/pdlp/python/pdlp_test.py .....F....                     [100%]
=================================== FAILURES ===================================
___________________________________ test_lp ____________________________________
Expected None, but test returned <ortools.pdlp.python.pdlp.QuadraticProgram object at 0x7fd4b600b170>. Did you mean to use `assert` instead of `return`?
=========================== short test summary info ============================
FAILED ../../../ortools/pdlp/python/pdlp_test.py::test_lp - Failed: Expected ...
========================= 1 failed, 9 passed in 1.40s ==========================
```