Feature/merge g9.5 (#70)
* fix

* add minimal highs interface

* [CP-SAT] more work on experimental linear propagation; fix #3483; start cleaning up the synchronization code

* add bazel to workspace

* Add KnapsackSolverTests.cs (Fix #3481)

* make: Fix makefile.dotnet.mk

* Fix ConstraintSolverTests.cs

* dotnet: Add FlowTests.cs (Fix #3482)

* expose missing MaxFlow::SetArcCapacity()

* makefiles comments fixup

* export from google3

* Add license boiler plate

* cmake: Fix highs_interface.cc

* cmake: Clean README.md

* cmake: prepare HiGHS support

* cmake: disable HiGHS by default

* cmake: Fix README.md

* java: Fix package in examples/java/

* cmake: explicitly depends on absl::time

* make: remove duplicate recipe

* make: cleanup

* comments typos

fixing minor grammar

* cmake: Readme fixup

* examples/java: fixup

* export from google3

* add knapsack_interface.cc

* pdlp: add samples

* highs fixup

* python: fixup

* examples/python: cleanup

* mathop update

* qap_sat solver and qap reader

* polish

* python example to solve a mps file

* [UTIL] fix test; support qap problems with objective

* [CP-SAT] move routing cuts it their own files; more work on new linear propagation

* misc

* missing files

* fix

* qap_sat: exit gracefully if no input file

* disable assert on windows; fix test

* [CP-SAT] rewrite square relaxation on cut generation; remove dead presolve code

* cmake: Add googletest for testing

* init: fixup

* algorithm: comment fixup

* linear_solver: google3 export

* math_opt format fixup

* base: add missing stuff

* Add mock-log.h
* Add zipfile and gzipfile mock
* Add filesystem mock
* Add memfile and mutablememfile mock
* Add numbers.h
* logging rework

* graph: fixup

* routing: Add test_data/

* google3: export routing/

* routing: random fixup

* Made comment consistent with documentation

* add C# Multiplication equality sample

* add C++ Multiplication equality sample

* add Python Multiplication equality sample

* Update windows-Ubuntu for manual trigger

* util/stats: use absl::string_view

* util: use std::mt19937_64

* base: Fix file::WriteString

don't close file in WriteString to have the same behaviour than in google3

* routing: fix file_name in test

* routing: Add F-n45-k4

* cmake: Rework CPLEX support (#3499)

* sat: Add NonLinearSat.java

* sat: remove non utf-8 unix character

note: run dox2unix in ortools/sat/samples/

* make: Fix sat samples list

* [CP-SAT] cleaning

* missing include

* [CP-SAT] coefficient strenghtening

* [CP-SAT] more presolve on linear

* vscode: Fix code-workspace

* sat(java): fix typo in comment

* make: Fix rules overwrite

* pdlp: Fix java package

* cmake: Fix java.cmake

* routing: Add VRP Solution Callback (#3300)

* routing: VrpSolutionCallback cleanup

* routing: export from google3

some performance increase:
* lazy initialization
* filter dynamic sorting
* better lifo management
* use_node_pair_swap_active: BOOL_FALSE

* routing: Fix export

* constraint_solver: merge pywraprouting_test.py and routing_api_test.py

* Bugfixes for cover_rectangle example

* fix symmetry breaking

* cmake(dotnet): Fix dependency

dotnet_package was not rebuild when dotnet_native_package change

* cmake(java): Fix dependency

java_package was not rebuild when java_native_package change

* make: disable test build

* cmake(python): cleanup

* routing(csharp): Clean tests

Signed-off-by: Corentin Le Molgat <corentinl@google.com>

* routing(java): Clean tests

* routing(python): Fix format in test

* routing(swig): Expose SimpleBoundCost related methods (Fix #1815)

* Extract BoundCost from SimpleBoundCost since SWIG do not support
nested class
* Wrap it in all languages
* Expose new API
  * SoftSpanUpperBoundForVehicle
  * QuadraticCostSoftSpanUpperBoundForVehicle
* Add tests

* routing: fix lint in samples/

* fix bug in glop

* polish/reindent graph python wrappers and samples

* [CP-SAT] reorganize synchronization code; improve linear cuts strenthening

* fixed a few dead links

* util: Add rounding_modes_benchmark.cc

* math_opt: export from google3

* constraint_solver: export from google3

* base: fix format

* routing: fix best value in data

* make: Fix pdlp samples

* make: fix test_cpp_model_viewer

* routing: fix indent

* cmake(python): Add BUILD_VENV option

* make: Fix python test run

* slight changes to the relative links

* cmake: Update README.md

* Fix pywraprouting_test.py

* Add python 3.11 support (#3515)

* routing(python): Add FirstSolutionStrategy and LocalSearchMetaheuristic (#3364)

* routing(python): test fixup

* update python notebooks

* add model and solution fingerprinting to CP-SAT; cleanup old hash code; incorporate fast_hash in the codebase

* fix

* base: format hash.h

* bazel: remove dead dependency

now fast_hash is vendored in base/hash.cc

* release: Fix macos arm64 build

* release: Fix python whl naming

* [CP-SAT] improve deterministic search code

* [FLATZINC] remove num_solution/-n options

* fix crash

* [CP-SAT] fix deterministic mode

* tools/docker: fix python amd64 manylinux build

* base: Fix hash.cc (Fix #3537)

* fix compilation of fasthash64 on windows

* swig: Fix python build when using swig 4.1.0

* swig: Fix java build when using swig 4.1.0

* swig: Fix dotnet build when using swig 4.1.0

* tools/docker: Fix dockerfile

* [CP-SAT] fix interleave_search; minor code improvements

* [ROUTING] use standard <random>

* [GRAPH] check connectivity in the eulerian_path

* comment

* [GLOP] optimize pivoting

* ci: Bump macos to Python 3.11

* routing: disable broken tests

todo(mizux): fix file path management

* python: copy pdlp python sample

* make: fix archive_python

* [LP-DATA] fix USE_LP_PARSER=OFF build

* [CP-SAT] make clause sharing deterministic with interleave_search=true

* tentative fix for glop build

* tools/docker: Fix export

* add time limit

* [GLOP] improve internals

* tweaks

* tools/release: fix windows test

* [GLOP] tweaks and improvements

* polish python examples

* try to fix lp_test_api.py

* try to fix another example

* tentative fix freebsd

* allow Xpress to be loaded dynamically into OR-Tools

* [GLOP] unrolling

* fix infeasible LNS, was a bug in cumulative presolve

* [CP-SAT] add more parameter validation; fix fuzzer bug on int_prod

* dotnet: rework lang version

* dotnet: rework RID management

* dotnet: rework TFM management

* dotnet: Add more optional TFM (disable by default)

* fix define of XPRS_CC depending of OS

* fix format

* [CP-SAT] better fix for int_prod

* [CP-SAT] improve processing of hints; fix bug with median_value heuristic; misc cleanup

* bazel: bump pybind11 v2.10.0 -> v2.10.1

* cmake: Bump pybind11 v2.10.0 -> v2.10.1

* bazel: Bump pybind11_bazel

* speed up matrix computation

* [CP-SAT] fix 3 bugs

* remove USE_XPRESS cmake variable as well as XPRESS_ROOT and XPRESS_PATH

* remove useless Xpress typedef and create printXpressBanner method

* gurobi: Rework path (Fix #3548)

* cmake(ci): Bump FreeBSD to python3.9

* [CP-SAT] fix integer reasons; use fast_hash to fingerprint equations

* [CP-SAT] rewrite cut code

* ci: fix FreeBSD python

* python: FreeBSD fixup

* [CP-SAT] fix sat_interface after new parameter validation; support symmetry detection for bool_and with multiple enforcement literals

* tools/release: fixup

* [CP-SAT] add lin_max presolve; fix bug in int_prod

* dotnet: Rework C# lang version

* use 9.0 for building library
* use 8.0 when building samples

* tools/release: add log

* dotnet: remove netstandard2.0 (unsupported)

ortools\sat\csharp\CpSolver.cs(214,25): error CS1061: 'Queue<Term>' does not contain a definition for 'TryDequeue' and no accessible extension method 'TryDequeue' accepting a first argument of type 'Queue<Term>' could be found

* dotnet: Add net46,net461,net462 support

* tools/release: enable net46 on windows

* util: Update rouding_modes_benchmark.cc

* [CP-SAT] fix potential check failed in presole

* [GLOP] Speedups

* log status error when not found xpress library

* add XpressIsCorrectlyInstalled method

* initXpressEnv returns a bool instead of int and allows verbosity or not

* more unrolling

* [CP-SAT] fix fuzzer bugs; add presolve/merging of boolean constraints to help reduction/linear relation

* speed up bitset

* closed model in vrp_initial_routes

* fixed comment

* tweaked comment

* tools/release: remove macos python3.6 support

* tools/release: Bump make check to 4.4 on macos

* tools/docker: disable python artifacts generation

* clean trailing white space

* log Xpress Optimizer version when loaded and log that XPRESS env variable does not exist

* remove xprs from pipelines building matrix and remove XPRESS_ROOT

* Adding xpress version info

* Adding example use for Xpress solver

* always print problem with license

* Adding doc on Xpress env vars

* update Xpress logs

* Removing call to XPRSgetbanner if XPRSinit fails

* notebooks: sync

* tools/docker: Fix debian-sid

version returned by lsb-release is 'n/a' which break all scripts...

* Removing fork specific CI

* add parse_header_xpress.py script

* remove FindXPRESS.cmake and update ortoolsConfig.cmake.in

* Factorize useXpress calls

* update logs when Xpress could not be loaded or when license error

* Changing temporarily xpress repos

* Cleaning other workflows

* Changing temporirly xpress repo in centos.yml

* Changing xpress checkout for centos.yml

* Printing CMake version

* Installing cmake 3.25.1 for centos instead of 3.17

* Downgrade to cmake 3.22.0

* Moving cmake install to cwd dir

* Fixing cmake install

* Trying predefined cmake github action installer

* Renaming cmake3->cmake

* Renaming ctest3->ctest

* Clean tautology

Co-authored-by: Florian Omnès <florian@omnes.cc>

* update parse_header_xpress.py

* Resetting Xpress repo on Centos

* Resetting Xpress repos on Ubuntu-Windows

---------

Signed-off-by: Corentin Le Molgat <corentinl@google.com>
Co-authored-by: Laurent Perron <lperron@google.com>
Co-authored-by: Corentin Le Molgat <corentinl@google.com>
Co-authored-by: Mizux Seiha <mizux.dev@gmail.com>
Co-authored-by: ssge <george.kremenliev@gmail.com>
Co-authored-by: watchdogs132 <ankanbose56@gmail.com>
Co-authored-by: Alexander Ignatovich <cadbimdeveloper@yandex.ru>
Co-authored-by: Antony Phillips <antony.e.phillips@gmail.com>
Co-authored-by: Arthur Godet <arthur.godet@artelys.com>
Co-authored-by: ArthurGodet <arth.godet@gmail.com>
Co-authored-by: Florian Omnès <florian@omnes.cc>